version: "3.9"

services:
  dynamodb:
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
    environment:
      AWS_ACCESS_KEY_ID: "fakeMyKeyId"
      AWS_SECRET_ACCESS_KEY: "fakeSecretAccessKey"
      AWS_REGION: us-east-1