package org.example.lambda.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
@DynamoDBTable(tableName = "brd_lambda_data")
public class Address {

    /**
     * id.
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    /**
     * location.
     */
    @DynamoDBAttribute
    private String location;

    /**
     * line1.
     */
    @DynamoDBAttribute
    private String line1;

    /**
     * line2.
     */
    @DynamoDBAttribute
    private String line2;

    /**
     * line3.
     */
    @DynamoDBAttribute
    private String line3;
}
